version: "3.8"

services:
  app:
    build:
      args:
        user: alex
        uid: 1000
      context: .
      dockerfile: docker/php/Dockerfile
    image: ip-geo-locator-app
    container_name: ip-geo-locator-app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - nginx
    #            - db
    volumes:
      - .:/var/www/html:delegated
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - ip-geo-locator

  nginx:
    image: nginx:1.17-alpine
    container_name: ip-geo-locator-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - ip-geo-locator

  redis:
    image: redis:7.0-rc2
    container_name: ip-geo-locator-redis
    volumes:
      - ./data/storage/redis/data:/data
    ports:
      - '6380:6380'
    networks:
      - ip-geo-locator

  redisinsight:
    image: redislabs/redisinsight:1.11.1
    container_name: ip-geo-locator-redisinsight
    ports:
      - '8001:8001'
    networks:
      - ip-geo-locator

#    db:
#        image: postgis/postgis:12-master
#        container_name: ip-geo-locator-db
#        restart: unless-stopped
#        volumes:
#            - ./db/atlas_db:/var/lib/postgresql/data
#        env_file: ./docker/envs/db.env
#        command: postgres
#        ports:
#            - "5432:5432"
#        networks:
#            - ip-geo-locator

networks:
  ip-geo-locator:
    driver: bridge